<?php

/**
 * Built-in copy for the system pages, in the two source languages
 * (Simplified Chinese and English). Every other locale is either an
 * administrator translation or falls back to English.
 *
 * Regenerated by bin/migrate.php consumers; edit the Markdown below (or the
 * admin console) and re-run:  php bin/migrate.php --seed-only
 *
 * @return array<string,array{titles:array<string,string>,contents:array<string,string>}>
 */

return array (
  'about' => 
  array (
    'is_system' => 1,
    'sort_order' => 1,
    'titles' => 
    array (
      'zh-CN' => '关于本站',
      'en' => 'About this site',
    ),
    'contents' => 
    array (
      'zh-CN' => '# 关于本站

**AthenXiv** 是一个开放的论文发布与存证平台。名字取自拉斐尔的名画《雅典学院》——那幅画里没有学位袍，没有头衔牌，只有一群人在争论。我们想做的是同一件事：**不问出身，只问论证。**

---

## 一、AGI 时代，知识边界应当属于每一个人

随着 AGI 时代的到来，人类对知识边界的拓展正在变得触手可及。就在不久前，大型语言模型还只是「会写字的工具」；而如今，它们已经开始站到真正的新成果之中——在与数学家合作时，GPT-5 为悬置数十年的 Erdős 第 848 号问题补上了证明中缺失的一环，让人们第一次看到模型参与到「还没有人知道的结论」里，而不只是复述已知的知识。

这当然是好消息。但当探索的能力越来越集中在少数机构、少数模型和少数预算手中，一个自然的问题就会浮现：**谁来提出问题？谁有资格得出结论？谁又有权把它发表出来？**

我们的答案很明确：**这种探索的权利，以及把探索结果公诸于众的权利，应当属于每一个人。** 它不该等到某个机构点头，也不该先过一遍学位、职称与经费的筛选。谁都可以提出猜想、给出证明、写下反驳——这正是本站存在的理由。

你或许没有昂贵的算力，也没有挂在墙上的头衔，但这些从来不是「能否参与」的前提。本站想做的，是让想法本身被看见、被记录、被验证。

---

## 二、没有 DOI，但有可证实的优先权

与成熟的预印本平台不同，本站目前**无法为论文分配 DOI**。但我们能做另一件事，而且我们认为它同样重要：

**本站为每一篇上传的论文提供 OpenTimestamps 时间戳存证。** 论文的发布日期因此得到一份**具有可证实效益的时间戳验证**，从而保护发布者对于这项研究的**优先权**——即便论文尚未被任何期刊收录，你「何时想到了它、何时写下了它」也已经留有凭证。

这是本站最不像「普通预印本网站」的地方。

论文上传的那一刻，系统会对每个文件计算 SHA-256 摘要，并把摘要提交给公开的 OpenTimestamps 日历，最终锚定到**比特币区块链**上。你会拿到一份 `.ots` 存证文件，它可以：

* **离线验证**——用官方客户端或 opentimestamps.org 的网页，在你的浏览器里完成校验，不需要相信本站，也不需要本站还活着；
* **精确到字节**——证明的是「这个文件在某个时刻已经存在」，改动一个标点，验证就会失败；
* **免费、永久、可公开引用**——不收费、不限制下载、不需要注册就能下载别人的存证。

在预印本平台里，**默认给每一篇投稿（包括最终没被接收的稿件）做区块链时间戳存证的，仍然很少见**。它真正保护的是你的**优先权**：

* 投稿被拒，存证依然有效——存证针对的是文件，不是我们的评审意见；
* 论文后来被下架、撤回，甚至本站不再运营，存证依然可以独立验证；
* 万一遭遇剽窃、洗稿或优先权争议，你可以拿出这份证明，而不是只能翻聊天记录和邮件时间。

**存证与审核同时进行**：你点下「提交」的瞬间，存证就已经完成，不必等审核结果。

顺带一提，不只是论文：**本站自己的介绍、指南与政策页面，也都逐页做了同样的时间戳存证**。你可以在这些页面下方下载存证文本与 `.ots` 证明，自行校验它们自发布以来是否被改动过——我们希望连「本站是什么、主张什么」这件事，也是可以被独立验证的。

---

## 三、低门槛、真开放

* 本站**同时接收正式论文与预印本**，不要求同行评议通过，不要求机构背书；
* **不限学历、不限职称、不限单位、不限推荐人**，任何人均可注册并上传；
* 欢迎独立研究者、民间学者、跨学科作者，以及不在学院体系内但认真写作的人；
* 审核的门槛设在「**能不能读懂、论证是否自洽、材料是否完整**」，而不是「你是什么身份」；
* 一次投稿不成立，可以修改后重新提交；被拒稿不影响你的存证，也不影响你继续投稿。

我们相信这恰好是「AthenXiv」这个名字的意思：广场上站着的人，谁都可以开口。

---

## 四、多语言、多学科

* 界面支持**三十种语言**，会根据你的浏览器语言自动切换；
* 论文正文的语言由你自己选择：列表里没有的语种，可以直接填写，审核通过后它会自动出现在语言筛选栏里；
* 学科分类**多级嵌套**，覆盖数学、物理、化学、生物、医学、工程、经济、心理、语言、历史、哲学、艺术等常见学科及其分支。

---

## 五、我们拒绝什么（严肃声明）

**本站拒绝伪科学论文与一切学术造假。** 具体包括但不限于：

1. 违背基本科学事实、以「推翻」现有科学结论为卖点却没有任何可检验证据的所谓研究；
2. 数据、图表、引文造假，或隐瞒关键来源；
3. 抄袭、代写、AI 洗稿等不诚实的署名行为；
4. 冒用他人身份、伪造单位或伪造合作者信息；
5. 反复提交已被明确判定为造假的同一内容。

一经确认，我们会**下架论文、封禁账号、保留完整审计记录**，并保留公开说明的权利。请理解一条底线：

> **时间戳只证明「某个文件在某时刻已经存在」，它不证明这个文件的内容正确。**
> 我们绝不会用存证为伪科学或造假背书；同样，任何人也不应把「有存证」当成「有道理」。

---

## 六、如何开始

1. [注册一个账号](/register)——只需要昵称和一个邮箱；
2. 准备一份 PDF，填写标题、摘要、作者与关键词；
3. [上传论文](/submit)——上传完成即自动完成时间戳存证；
4. 编辑会对论文分区（一区／二区／三区／预印本等），此后论文即可被检索、引用与下载；
5. 个人主页、ORCID 与学术平台链接都可以自由配置。

如对本站有建议、举报或合作意向，见页脚的联系邮箱。',
      'en' => '# About this site

**AthenXiv** is an open platform for publishing and timestamping papers. The name comes from Raphael\'s *The School of Athens* — a painting with no gowns, no title plates, just people arguing. That is the idea here: **we do not ask who you are, only whether the argument holds.**

---

## 1. In the age of AGI, the frontier of knowledge should belong to everyone

With the arrival of the AGI era, the human frontier of knowledge is coming within reach. Not long ago, large language models merely produced text; today they are beginning to stand inside genuine new results. Working with mathematicians, GPT-5 supplied the missing step in the proof of Erdős Problem 848 — a question that had stood open for decades — and for the first time many of us saw a model contribute to a conclusion nobody yet knew, rather than restating what was already known.

That is good news. But when the ability to explore concentrates into a few institutions, a few models and a few budgets, an obvious question follows: **who gets to pose the question? Who is allowed to reach the conclusion? And who holds the right to publish it?**

Our answer is plain: **the right to explore, and the right to publish what that exploration finds, should belong to everyone.** It should not wait for an institution\'s nod, nor pass first through a filter of degrees, titles and grants. Anyone may propose a conjecture, give a proof, write a rebuttal — that is why this site exists.

You may have neither expensive compute nor a title on a wall, but neither was ever a precondition for taking part. What this site tries to do is let an idea itself be seen, recorded and checked.

---

## 2. No DOI — but a priority you can verify

Unlike established preprint servers, this site **cannot assign a DOI** to a paper. There is something else we can do, and we think it matters just as much:

**Every paper uploaded here is given an OpenTimestamps proof.** Its publication date is therefore backed by a **verifiable timestamp**, which protects the author\'s **priority** over the work — even if no journal has accepted it, when you thought of it and when you wrote it down is on the record.

This is what makes the site unlike an ordinary preprint server.

The moment a paper is uploaded, every file is hashed with SHA-256 and the digest is submitted to public OpenTimestamps calendars, which anchor it in the **Bitcoin blockchain**. You receive an `.ots` proof that is:

* **independently verifiable** — check it in your own browser at opentimestamps.org or with the official client; no need to trust us, or for this site to still exist;
* **byte-exact** — it proves *this* file existed at that moment; change one punctuation mark and verification fails;
* **free, permanent and citable** — no fee, no download limits, no account needed to download anyone\'s proof.

**Doing this by default for every submission — including papers that are never accepted — is still rare among preprint platforms.** What it protects is your **priority**:

* a rejection does not invalidate the proof: the proof is about the file, not about our opinion;
* a withdrawn or taken-down paper keeps a valid proof that outlives this site;
* in a plagiarism or priority dispute you can produce a cryptographic receipt instead of digging through e-mails.

**Timestamping happens in parallel with review**: the proof is created the moment you press submit.

One more thing, and it is not only about papers: **this site\'s own introduction, guidelines and policy pages carry the same proof, page by page.** At the bottom of each of them you can download the stamped text and its `.ots` proof and check for yourself that they have not changed since the day they were published. Even what this site is, and what it claims, should be independently verifiable.

---

## 3. Low barriers, genuinely open

* We host **both formal papers and preprints**; peer-review acceptance is not required, nor is institutional backing;
* **No degree, position, affiliation or sponsor is required** — anyone may register and upload;
* Independent researchers, non-academic scholars and cross-disciplinary authors are explicitly welcome;
* Review asks whether a submission is **legible, self-consistent and complete**, not who wrote it;
* A rejected submission can be revised and resubmitted; rejection never invalidates your proof.

We take this to be the meaning of the name: in the School of Athens, anyone may speak.

---

## 4. Many languages, many disciplines

* The interface ships **thirty languages** and follows your browser automatically;
* You choose the language of the text itself; if it is not in the list, type it in — once the paper is accepted, it appears in the language filter;
* Subject areas are **nested and multi-level**, covering mathematics, physics, chemistry, biology, medicine, engineering, economics, psychology, linguistics, history, philosophy, the arts and their branches.

---

## 5. What we refuse (a serious statement)

**This site refuses pseudoscientific papers and all academic fraud**, including but not limited to:

1. claims that "overturn" established science while offering no testable evidence;
2. fabricated data, figures or citations, or concealed sources;
3. plagiarism, ghost-writing or laundering machine-generated text into false authorship;
4. impersonation, invented affiliations or fabricated co-authors;
5. repeatedly resubmitting material already found to be fraudulent.

Confirmed cases are **taken down, the account is banned and the audit trail is kept**. One boundary deserves stating plainly:

> **A timestamp proves that a file existed at a moment; it does not prove that its contents are correct.**
> We will never let a proof lend authority to pseudoscience — and nobody should read "it has a timestamp" as "it is true".

---

## 6. Getting started

1. [Create an account](/register) — a display name and an e-mail address are enough;
2. Prepare a PDF and fill in title, abstract, authors and keywords;
3. [Upload it](/submit) — the timestamp proof is created immediately;
4. An editor assigns the paper to a section (Tier 1/2/3, preprints, …); afterwards it is searchable, citable and downloadable;
5. Profile pages, ORCID and academic/social links are yours to configure.

For suggestions, reports or collaboration, use the contact address in the footer.',
    ),
  ),
  'guidelines' => 
  array (
    'is_system' => 1,
    'sort_order' => 2,
    'titles' => 
    array (
      'zh-CN' => '投稿指南',
      'en' => 'Submission guidelines',
    ),
    'contents' => 
    array (
      'zh-CN' => '# 投稿指南

## 一、谁可以投稿

**任何人。** 不限学历、职称、单位与推荐人，不要求同行评议通过，不要求机构邮箱。我们欢迎独立研究者、民间学者、跨学科作者与仍在学习中的作者。

## 二、必须准备的材料

| 材料 | 要求 | 是否必须 |
| --- | --- | --- |
| 论文 PDF | 完整的正文，含标题、作者、参考文献 | **必须** |
| 摘要 | 至少 40 个字符，描述问题、方法与结论 | **必须** |
| 标题 | 简明准确 | **必须** |
| 作者列表 | 按署名顺序，可填写单位、邮箱、ORCID | 必须（至少一位） |
| 关键词、许可协议、DOI | 便于检索与引用 | 可选 |
| 附件压缩包 | 数据、代码、图表等，支持 zip / 7z / rar / tar.gz 等 | 可选 |
| 附加链接 | 相关的 arXiv、代码仓库、数据集、幻灯片、视频、博客 | 可选 |

## 三、上传之后会发生什么

1. **立即存证**：系统对 PDF 与每个附件计算 SHA-256，并提交到公开的 OpenTimestamps 日历，生成可下载的 `.ots` 证明。存证与审核结果无关，被拒稿也依然有效。
2. **编辑审核**：编辑检查稿件是否可读、是否自洽，并决定分区（一区／二区／三区／预印本等）。可能通过、打回或要求修改；打回时会给出理由。
3. **公开与检索**：通过审核后论文进入公开列表、分区页与站点地图，可被引用、下载与检索；你也可以随时**撤回**自己的论文（撤回不会删除存证）。

## 四、版本更新

论文可以**更新版本**：在「我的论文 → 编辑」中上传新的 PDF，系统会保留旧版本文件与其**独立的时间戳存证**，新版本会获得一份新的存证。每一版的摘要与文件都可以分别下载，引用时也可以注明版本号。

## 五、我们拒绝的稿件

* 违背基本科学事实、以「推翻」为名却无可检验证据的伪科学稿件；
* 数据、图表或引文造假，隐瞒关键来源；
* 抄袭、代写、AI 洗稿等不诚实署名；
* 冒用他人身份、伪造单位或伪造合作者；
* 与学术无关的广告、营销与人身攻击内容。

一经确认，我们会下架论文、封禁账号并保留审计记录。请记住：**存证只证明文件在某时刻存在，不代表内容正确。**

## 六、成本与版权

上传、存证、下载**全部免费**。你保留自己作品的著作权；请在投稿时选择许可协议（如 CC BY 4.0），以便他人合法引用与传播。上传即表示你确认拥有所提交材料的发布权。',
      'en' => '# Submission guidelines

## 1. Who may submit

**Anyone.** No degree, position, affiliation or sponsor is required, no peer-review acceptance and no institutional e-mail. Independent researchers, non-academic scholars, cross-disciplinary and early-career authors are all welcome.

## 2. What a submission must contain

| Item | Requirement | Required |
| --- | --- | --- |
| Paper PDF | Full text with title, authors and references | **Yes** |
| Abstract | At least 40 characters describing problem, method, result | **Yes** |
| Title | Concise and accurate | **Yes** |
| Authors | In credit order, with optional affiliation, e-mail, ORCID | Yes (at least one) |
| Keywords, licence, DOI | Helps discovery and citation | Optional |
| Archive attachment | Data, code, figures (zip / 7z / rar / tar.gz …) | Optional |
| External links | Related arXiv entry, repository, dataset, slides, video, blog | Optional |

## 3. What happens after uploading

1. **Immediate timestamping** — the PDF and every attachment are hashed with SHA-256 and submitted to public OpenTimestamps calendars; you get a downloadable `.ots` proof. This is independent of review and survives rejection.
2. **Editorial review** — an editor checks legibility and self-consistency and assigns a section (Tier 1/2/3, preprints, …). The submission may be accepted, sent back for changes, or rejected with a stated reason.
3. **Publication** — accepted papers appear in the archive, the section pages and the sitemap, and become citable, downloadable and searchable. You may **withdraw** your own paper at any time; withdrawal never deletes the proof.

## 4. New versions

Papers can be **versioned**: upload a new PDF from *My papers → Edit*. Earlier files and their **separate timestamp proofs** are preserved, and the new version receives its own proof. Every version can be downloaded and cited individually.

## 5. What we reject

* pseudoscientific work that "overturns" established science without testable evidence;
* fabricated data, figures or citations, or concealed sources;
* plagiarism, ghost-writing or laundering generated text into false authorship;
* impersonation, invented affiliations, fabricated co-authors;
* advertising, marketing and personal attacks unrelated to scholarship.

Confirmed cases are taken down, the account banned and the audit trail kept. Remember: **a proof shows that a file existed at a time; it does not certify that its contents are correct.**

## 6. Cost and copyright

Uploading, timestamping and downloading are **free**. You keep the copyright to your work; please choose a licence (for example CC BY 4.0) so others may cite and redistribute it legally. Uploading confirms that you hold the rights to publish the material.',
    ),
  ),
  'athenaeum' => 
  array (
    'is_system' => 1,
    'sort_order' => 3,
    'titles' => 
    array (
      'zh-CN' => '关于 AthenXiv',
      'en' => 'About AthenXiv',
    ),
    'contents' => 
    array (
      'zh-CN' => '# 关于 AthenXiv

## 名字

**AthenXiv** 由两半拼成：**Athena**（雅典娜——智慧与技艺之神，也是柏拉图学园所供奉的神）与 **-Xiv**（archive 的尾巴，也是 arXiv 一类论文库的后缀）。合起来是「雅典娜的文库」，一句话：**一个让人读书、辩论、留下文字，也留下证据的地方。**

我们并不假称它是古希腊的某个机构。它是一个刚刚造出来的词，只为说明一件很小的事——把论文写下来，把上传的那一刻钉在一个不由我们掌控的时钟上。
## 本站是什么

* 一个**论文发布平台**：注册、投稿、审核、分区、检索、引用、下载；
* 一个**存证平台**：上传即写入 OpenTimestamps，锚定比特币区块链，`.ots` 证明可独立验证；
* 一个**多语言、多学科**的开放档案：界面 30 种语言，学科多级分类，从数学、物理、化学、生物、医学延伸到哲学、历史与艺术等；
* 一件**不依赖任何机构、任何资助、任何推荐人**就能运行的小工具。

## 本站不是什么

* 不是同行评议期刊，不提供影响因子，不承诺「发表即认可」；
* 不为伪科学或造假提供展示位——存证保护的是诚实作者的优先权，不是错误主张的曝光量；
* 不主张时间戳能证明内容正确：它只回答「这个文件在什么时候已经存在」这一个问题。

## 技术上是怎样搭起来的

* 纯 PHP 编写，不依赖 Composer 与前端构建工具，普通虚拟主机即可部署；
* 数据存于 MySQL（本地验证可用 SQLite）；
* PDF 在线阅读使用开源的 **PDF.js**，含中日韩字体映射；
* 时间戳使用公开的 OpenTimestamps 日历，证明文件由本站自行解析、合并与升级；
* 论文 PDF 与存证文件存放在 Web 根目录之外，只能通过带权限校验的程序端点访问。

## 联系与反馈

功能建议、内容举报、合作意向，请写信给页脚列出的联系邮箱。我们尤其欢迎关于**分类体系**与**审核标准**的批评。

> 未经省察的人生不值得过。
> ——苏格拉底（柏拉图《申辩篇》38a）',
      'en' => '# About AthenXiv

## The name

**AthenXiv** is a portmanteau: **Athena** — the goddess of wisdom and craft, and the patron of Plato\'s Academy — plus **-Xiv**, the tail of *archive* (and of arXiv-style repositories). "Athena\'s archive": **a place where people read, argue, leave a written record, and leave proof of when they did it.**

We do not pretend it names an ancient institution. It is a freshly coined word for one small job: put the paper down in writing, and nail the moment of upload to a clock nobody here controls.
## What this site is

* a **publishing platform**: register, submit, get reviewed, be assigned a section, be found, be cited, be downloaded;
* a **timestamping service**: uploading writes an OpenTimestamps proof anchored in Bitcoin, verifiable independently;
* a **multilingual, multi-disciplinary archive**: thirty interface languages, nested subject areas running from mathematics, physics, chemistry, biology and medicine through to philosophy, history and the arts;
* a **small tool that needs no institution, no grant and no sponsor** to run.

## What it is not

* not a peer-reviewed journal: no impact factor, no promise that publication equals endorsement;
* not a stage for pseudoscience or fraud — a proof protects the priority of honest authors, it does not amplify false claims;
* not a claim that a timestamp certifies correctness: it answers exactly one question, *when did this file exist*.

## How it is built

* plain PHP, no Composer and no front-end build step — an ordinary shared host is enough;
* data lives in MySQL (SQLite is supported for local verification);
* in-browser reading uses open-source **PDF.js**, including CJK font maps;
* timestamping uses the public OpenTimestamps calendars, with proofs parsed, merged and upgraded by this application itself;
* paper files and proofs live outside the web root and are only reachable through permission-checked endpoints.

## Contact

Feature requests, content reports and collaboration: write to the address in the footer. Criticism of our **taxonomy** and **review standards** is especially welcome.

> The unexamined life is not worth living.
> — Socrates (Plato, *Apology* 38a)',
    ),
  ),
  'timestamping' => 
  array (
    'is_system' => 1,
    'sort_order' => 4,
    'titles' => 
    array (
      'zh-CN' => '时间戳存证如何运作',
      'en' => 'How timestamping works',
    ),
    'contents' => 
    array (
      'zh-CN' => '# 时间戳存证如何运作

## 一句话

上传论文时，系统会把文件的 SHA-256 摘要提交给公开的 OpenTimestamps 日历，最终写入**比特币区块链**。你得到一份 `.ots` 证明，可以在自己的浏览器里独立验证，**不需要相信本站，也不需要本站继续存在**。

## 逐步说明

1. **本地计算摘要**：本站用 SHA-256 计算每个文件（PDF 与每个附件）的 32 字节摘要。**只有摘要离开服务器，论文内容从不外发。**
2. **提交日历**：摘要同时提交给多个公开的 OpenTimestamps 日历（聚合器）。每个日历返回一段运算链，证明它在该时刻接收了这份摘要。
3. **生成证明**：这些运算链被合并并保存为 `.ots` 文件，附带在你的论文页面上，任何人可下载。
4. **等待确认**：日历把这些摘要汇总进一棵 Merkle 树并写入比特币交易。交易进入区块通常需要 1–3 小时。本站会定时（以及在你浏览论文页时）自动向日历查询升级，把「待确认」的证明替换为带**区块高度**的完整证明。
5. **独立验证**：下载 `.ots`，打开 <https://opentimestamps.org/#stamp-and-verify>，把证明文件（连同 PDF 可选）拖进验证区，浏览器会在本地重算整条运算链并比对区块头。

## 它能证明什么，不能证明什么

| 能证明 | 不能证明 |
| --- | --- |
| 该文件在某个比特币区块时刻**已经存在** | 内容是否正确、是否原创、是否重要 |
| 文件自那时起**未被修改**（改动一个字节即验证失败） | 作者是谁、署名是否真实 |
| 存证时间**不依赖于本站**的诚实（可自行验证） | 论文是否经过同行评议 |

**注意**：在证明尚未获得比特币确认时，日历只记录了它的 URI——证明里没有任何时间信息。此时页面显示的「提交时间」是本站自己记录的时间，我们明确标注它尚未获得密码学锚定；只有确认后才会显示区块时间。

## 为什么这对作者重要

* **优先权**：被拒稿、撤回、下架乃至本站停止运营，都不影响存证的效力；
* **举证**：遭遇剽窃或洗稿时，可以拿出与文件逐字节绑定的证明，而不是只有邮件和聊天记录；
* **成本**：对作者免费，对读者免费，对引用者免费；
* **公开**：任何人都能下载并验证，包括审稿人、编辑、期刊与法院。

## 日历与隐私

本站默认使用的公开日历：

* https://a.pool.opentimestamps.org
* https://b.pool.opentimestamps.org
* https://a.pool.eternitywall.com
* https://ots.btc.catallaxy.com

它们由社区捐赠运营，无需注册、无 API 密钥。**本站只提交摘要**：日历看到的是一串 32 字节的随机数，无法反推出论文内容、标题或作者。',
      'en' => '# How timestamping works

## In one sentence

When you upload a paper, the SHA-256 digest of every file is submitted to public OpenTimestamps calendars and ends up anchored in the **Bitcoin blockchain**. You receive an `.ots` proof that can be verified in your own browser — **without trusting this site, and without this site still existing**.

## Step by step

1. **Hash locally.** Each file (the PDF and every attachment) is hashed with SHA-256. **Only the 32-byte digest leaves this server; the contents of your paper never do.**
2. **Submit to calendars.** The digest is sent to several public OpenTimestamps calendars (aggregators). Each returns an operation chain proving it accepted that digest at that moment.
3. **Build the proof.** The chains are merged and stored as an `.ots` file, offered for download on the paper page.
4. **Wait for confirmation.** Calendars aggregate digests into a Merkle tree and commit it in a Bitcoin transaction. That normally lands in a block within one to three hours. This site polls the calendars on a schedule (and opportunistically when a paper page is viewed) and replaces the pending proof with one carrying the **block height**.
5. **Verify independently.** Download the `.ots`, open <https://opentimestamps.org/#stamp-and-verify> and drop the proof (and optionally the PDF) into the verification area. Your browser recomputes the whole chain and compares it against the block header.

## What it proves — and what it does not

| Proves | Does not prove |
| --- | --- |
| The file **existed** at a given Bitcoin block time | that the content is correct, original or important |
| The file is **unchanged** since then (one altered byte fails) | who wrote it, or that the authorship is genuine |
| The proof is verifiable **without trusting this site** | that the paper was peer reviewed |

**Note:** while a proof is still pending, the calendar has recorded only its URI — the proof contains *no time information at all*. The "submitted at" date shown on such a page is this site\'s own record, and we label it as not yet cryptographically anchored. The block time appears once confirmed.

## Why this matters for authors

* **Priority**: rejection, withdrawal, takedown or this site going offline do not invalidate the proof;
* **Evidence**: in a plagiarism dispute you can produce a proof bound byte-for-byte to your file;
* **Cost**: free for authors, readers and citers;
* **Public**: anyone can download and verify it — reviewers, editors, journals, courts.

## Calendars and privacy

The public calendars used by default:

* https://a.pool.opentimestamps.org
* https://b.pool.opentimestamps.org
* https://a.pool.eternitywall.com
* https://ots.btc.catallaxy.com

They are donation-funded, need no registration and no API key. **Only the digest is submitted**: a calendar sees 32 opaque bytes and cannot recover your title, abstract or authorship.',
    ),
  ),
  'policy' => 
  array (
    'is_system' => 1,
    'sort_order' => 5,
    'titles' => 
    array (
      'zh-CN' => '用户政策',
      'en' => 'User policy',
    ),
    'contents' => 
    array (
      'zh-CN' => '# 用户政策

这份页面说明你在 AthenXiv 上传与发布内容时同意的规则。它不替代法律意见，只把双方的责任写清楚。

## 一、你要对上传的内容负责

* 你确认自己**拥有或已获授权**上传该论文及其附件，并且它的发布不侵犯他人的著作权、隐私权或其他权利。
* 若论文包含第三方材料（图表、数据集、较长引文），请确认你有权一并发布，并在文中注明来源。
* 论文中的署名须真实：不得把未参与工作的人列为作者，也不得把实际作者排除在外。

## 二、你授予本站的许可

* 你保留论文的著作权。上传不转移著作权。
* 你授予本站**非独占、免费**的许可：存储论文与附件、向公众提供在线阅读与下载、并为存证计算哈希。该许可在你要求撤下论文后终止（已生成的存证记录无法撤回，这是时间戳的性质）。
* 你自己选择的许可协议（如 CC BY 4.0）适用于论文本身，会显示在论文页上。

## 三、本站的立场

* **开放**：任何人都可以投稿，不要求学历、职称、机构或推荐人。
* **诚实**：伪科学、伪造数据与抄袭会被拒绝。**时间戳只能证明文件在某时刻存在，不能证明内容正确**。
* **可撤下**：若权利人提出有依据的异议，或内容违反本页规则，本站可以在通知作者后下架论文。

## 四、隐私

* 注册需要邮箱验证，仅用于登录、通知与找回密码。
* 我们不会出售或交换你的个人信息；公开页面上只会显示你在论文中填写的作者信息与个人主页中你选择公开的内容。

## 五、联系方式

有任何疑问，请写信到页脚中的联系邮箱。',
      'en' => '# User policy

This page sets out the rules you accept when you upload and publish material on AthenXiv. It is not legal advice; it simply makes both sides\' responsibilities explicit.

## 1. You are responsible for what you upload

* You confirm that you **own or are authorised to publish** the paper and its attachments, and that publishing them does not infringe anyone\'s copyright, privacy or other rights.
* If the paper contains third-party material (figures, datasets, extensive quotations), make sure you may publish it too, and credit the source.
* Authorship must be truthful: do not list people who did not contribute, and do not leave out people who did.

## 2. The licence you grant this site

* You keep the copyright to your paper. Uploading does not transfer it.
* You grant this site a **non-exclusive, royalty-free** licence to store the paper and attachments, to serve them for reading and download, and to hash them for timestamping. That licence ends when you ask for the paper to be taken down — except for the proofs already created, which cannot be withdrawn (that is what a timestamp is).
* The licence you choose for the paper itself (e.g. CC BY 4.0) applies to the paper and is shown on its page.

## 3. Where this site stands

* **Open**: anyone may submit — no degree, position, affiliation or sponsor is required.
* **Honest**: pseudoscience, fabricated data and plagiarism are refused. **A timestamp proves that a file existed at a time; it never certifies that the contents are correct.**
* **Reversible**: if a rights holder raises a substantiated objection, or the content breaks the rules on this page, the paper can be taken down after the author is notified.

## 4. Privacy

* Registration requires e-mail verification, used only for sign-in, notifications and password recovery.
* We do not sell or trade your personal information. Public pages show only the author details you enter on the paper and whatever you choose to publish on your profile.

## 5. Contact

Questions? Write to the contact address in the footer.',
    ),
  ),
);
